export default class Translator {

    static keys = {
        en: {
            error: "ERROR 404",
            slogan : "Your health, our priority",
            slide_1: "The application that helps you manage your daily health, alerts you in an emergency and facilitates your emergency care.",
            slide_2: "Connect your device with a single click to view your constants at any time.",
            slide_3: "Fill in your symptoms, personal information and location, we'll take care of the rest!",
            slide_4: "An emergency ? Urgent-E makes it easy for you to access the emergency department of your choice: the fastest, the closest or both!",
            next_page: "Next",
            skip: "SKIP",
            cancel: "CANCEL",
            finish: "FINISH",
            back_dashboard: "BACK TO DASHBOARD",
            dashboard: "Dashboard",
            go_to_emergency : "GO TO EMERGENCY",
            link_device : "LINK MY DEVICE",
            hello: "HELLO",
            alert_1: "RESPIRATORY DISTRESS",
            alert_2: "CONTACT EMERGENCY ASAP",
            ignore: "IGNORE",
            blood_pressure : "BLOOD PRESSURE",
            pulse : "PULS",
            saturation_o2 : "SATURATION O2",
            respiratory_rate : "RESPIRATORY RATE",
            blood_sugar : "BLOOD SUGAR",
            temperature : "TEMPERATURE",
            confidentiality: "Confidentiality",
            confi_1: "In the event of an emergency, your personal data will only be transferred to the emergency services of the hospital where you will be treated.",
            confi_2: "Your data will not be marketed or transmitted to external parties.",
            my_informations: "My Informations",
            my_info_1: "DESCRIPTIVE INFORMATION",
            name: "Name",
            firstname: "First Name",
            age: "Age",
            size: "Size",
            weight: "Weight",
            my_info_2: "ADMINISTRATIVE INFORMATION",
            address: "Address",
            phone_number: "Phone Number",
            social_security: "Social Security number",
            mutual: "Mutual",
            emergency_contact: "Emergency Contact",
            my_info_3: "MEDICAL INFORMATION",
            allergies: "Allergies",
            treatments: "Treatments",
            chronic_diseases: "Chronic Diseases",
            surgical_history: "Surgical History",
            required_field: "Required field",
            enter_age: "Enter an age",
            enter_size: "Enter a size",
            enter_weight: "Enter a weight",
            enter_phone_number: "Enter a phone number",
            enter_social_security: "Enter a Social Security number",
            emergency: "Emergency",
            what_brings_you: "What brings you to the emergency?",
            pain: "Pain severity",
            photo: "Photograph of the injury",
            connected_object: "Connected object",
            perimeter: "Perimeter",
            ambulance: "Request an ambulance",
            yes: "YES",
            no: "NO",
            enter_perimeter: "Enter a search perimeter",
            information_transferred: "Your information is being transferred",
            hospital: "Hospital",
            at: "at",
            is_ready: "is ready to take care of you",
            patient_number: "Patient Number",
            waiting_time: "Estimated waiting time"
        },
        fr: {
            error: "ERREUR 404",
            slogan : "Votre santé, notre priorité",
            slide_1: "L'application qui vous aide à gérer votre santé au quotidien, vous alerte en cas d'urgence et facilite votre prise en charge en service urgentiste.",
            slide_2: "Connectez votre appareil d'un simple clic pour consulter vos constantes à tout moment.",
            slide_3: "Renseignez vos symptômes, informations personnelles et localisation, nous nous chargeons du reste !",
            slide_4: "Une urgence ? Urgent-E vous facilite l'accès au service des urgences de votre choix : le plus rapide, le plus proche ou les deux !",
            next_page: "Suivant",
            skip: "PASSER",
            cancel: "ANNULER",
            finish: "TERMINER",
            back_dashboard: "RETOURNER AU TABLEAU DE BORD",
            dashboard: "Tableau de bord",
            go_to_emergency : "ALLER AUX URGENCES",
            link_device: "CONNECTER MON APPAREIL",
            hello: "BONJOUR",
            alert_1: "DÉTRESSE RESPIRATOIRE",
            alert_2: "CONTACTER LES URGENCES AU PLUS VITE",
            ignore: "IGNORER",
            blood_pressure : "TENSION",
            pulse : "POULS",
            saturation_o2 : "SATURATION O2",
            respiratory_rate : "FRÉQUENCE RESPIRATOIRE",
            blood_sugar : "GLYCÉMIE",
            temperature : "TEMPÉRATURE",
            confidentiality: "Confidentialité",
            confi_1: "En cas d'urgence, vos données personnelles ne seront transférées qu'aux services d'urgences de l'hôpital auquel vous serez traité.",
            confi_2: "Vos données ne seront pas commercialisées ou transmises à des parties extérieures.",
            my_informations: "Mes Informations",
            my_info_1: "INFORMATIONS DESCRIPTIVES",
            name: "Nom",
            firstname: "Prénom",
            age: "Âge",
            size: "Taille",
            weight: "Poids",
            my_info_2: "INFORMATIONS ADMINISTRATIVES",
            address: "Adresse",
            phone_number: "Numéro de Téléphone",
            social_security: "Numéro de Sécurité Sociale",
            mutual: "Mutuelle",
            emergency_contact: "Contact d'Urgence",
            my_info_3: "INFORMATIONS MÉDICALES",
            allergies: "Allergies",
            treatments: "Traitements",
            chronic_diseases: "Maladies Chroniques",
            surgical_history: "Antécédents Chirurgicaux",
            required_field: "Champs requis",
            enter_age: "Saisissez un âge",
            enter_size: "Saisissez une taille",
            enter_weight: "Saisissez un poids",
            enter_phone_number: "Saisissez un numéro de téléphone",
            enter_social_security: "Saisissez un numéro de Sécurité Sociale",   
            emergency: "Urgences",
            what_brings_you: "Qu'est ce qui vous amène aux urgences ?",
            pain: "Sévérité de la douleur",
            photo: "Photographie de la blessure",
            connected_object: "Objet connecté",
            perimeter: "Périmètre",
            ambulance: "Demander une ambulance",
            yes: "OUI",
            no: "NON",
            enter_perimeter: "Saisissez un périmètre de recherche",
            information_transferred: "Vos informations sont en cours de transfert",
            hospital: "L'hôpital",
            at: "au",
            is_ready: "est prêt à vous prendre en charge",
            patient_number: "Numéro de Patient",
            waiting_time: "Temps d'attente estimé à"
        }
    }

    static translate(key="", language="fr"){
        try {
            return Translator.keys[language][key];
        } catch (e) {
            throw new Error(`Can't translate "${key}" in "${language}" language`);
        }
    }
};